### ISSUE TITLE
Colorblindness accessibility issue in theme_v2.css included from default style.css

### ISSUE THREAD

**Issue by soccermitchy** [joe27g/EnhancedDiscord#125]
In your theme_v2.css on the EnhancedDiscord server, you have this block of CSS code:
```css
[mask="url(#svg-mask-status-offline)"] {
    mask: url(#svg-mask-status-online) !important;
}
```
However, for people with colorblindness, that makes it hard to tell whether someone is online or offline. Additionally, because that is not default behavior and there is no option for it (nor is it documented anywhere), users who may not know otherwise won't be able to revert that back to the original behavior, pre-EnhancedDiscord. I did this as a temporary fix in my own style.css to force it back to the original behavior:
```css
[mask="url(#svg-mask-status-offline)"] {
	mask: url(#svg-mask-status-offline) !important;
}
```

However, as I mentioned earlier, a user may not know how to do this. I propose that, if users want it, we have it as an option under theme settings whether to make offline users show with the same 'shape' as online users, or at the very least document somewhere some instructions on how to revert to the default Discord behavior.
